import { Router } from 'express';
import { writeFile } from 'fs/promises';
import { UpstreamProxy } from '../database';
import { authMiddleware, adminMiddleware, AuthRequest } from '../middleware/auth';

const router = Router();

const UPSTREAM_CONFIG_PATH = '/etc/squid/conf.d/upstreams.conf';

// Generate Squid upstream configuration
async function generateUpstreamConfig(): Promise<string> {
  const proxies = await UpstreamProxy.findAll({
    where: { enabled: true },
    order: [['priority', 'DESC']],
  });

  if (proxies.length === 0) {
    return '# No upstream proxies configured\n';
  }

  let config = '# Upstream Proxy Configuration\n';
  config += '# Auto-generated by Squache backend\n\n';

  proxies.forEach((proxy, index) => {
    const peerName = `peer_${proxy.id}`;
    
    // Define cache_peer for each upstream proxy
    if (proxy.username && proxy.password) {
      config += `cache_peer ${proxy.host} parent ${proxy.port} 0 no-query login=${proxy.username}:${proxy.password} name=${peerName}\n`;
    } else {
      config += `cache_peer ${proxy.host} parent ${proxy.port} 0 no-query name=${peerName}\n`;
    }

    // Create ACL for this proxy type
    if (proxy.type) {
      config += `acl upstream_${proxy.type} req_header X-Squache-Upstream ${proxy.type}\n`;
    }
    if (proxy.country) {
      config += `acl upstream_country_${proxy.country.toLowerCase()} req_header X-Squache-Country ${proxy.country}\n`;
    }
  });

  config += '\n# Routing rules\n';
  
  // Add routing rules based on headers
  proxies.forEach((proxy) => {
    const peerName = `peer_${proxy.id}`;
    
    if (proxy.country) {
      config += `cache_peer_access ${peerName} allow upstream_${proxy.type} upstream_country_${proxy.country.toLowerCase()}\n`;
    } else if (proxy.type) {
      config += `cache_peer_access ${peerName} allow upstream_${proxy.type}\n`;
    }
    config += `cache_peer_access ${peerName} deny all\n`;
  });

  config += '\n# Default to direct connections\n';
  config += 'always_direct allow all\n';

  return config;
}

// List upstream proxies
router.get('/', authMiddleware, async (req, res) => {
  try {
    const proxies = await UpstreamProxy.findAll({
      order: [['priority', 'DESC'], ['name', 'ASC']],
      attributes: { exclude: ['password'] },
    });

    res.json(proxies);
  } catch (error) {
    console.error('Upstreams list error:', error);
    res.status(500).json({ error: 'Failed to list upstream proxies' });
  }
});

// Add upstream proxy
router.post('/', authMiddleware, adminMiddleware, async (req: AuthRequest, res) => {
  try {
    const { name, type, host, port, username, password, country, city, provider, enabled, priority } = req.body;

    if (!name || !type || !host || !port) {
      return res.status(400).json({ error: 'Name, type, host, and port are required' });
    }

    const proxy = await UpstreamProxy.create({
      name,
      type,
      host,
      port,
      username: username || null,
      password: password || null,
      country: country || null,
      city: city || null,
      provider: provider || null,
      enabled: enabled !== false,
      priority: priority || 0,
    });

    // Regenerate Squid config
    try {
      const config = await generateUpstreamConfig();
      await writeFile(UPSTREAM_CONFIG_PATH, config);
      console.log('Upstream config regenerated');
      // TODO: Signal Squid to reload config
    } catch (configError) {
      console.error('Failed to update Squid config:', configError);
    }

    res.status(201).json({
      ...proxy.toJSON(),
      password: undefined,
    });
  } catch (error) {
    console.error('Upstream create error:', error);
    res.status(500).json({ error: 'Failed to create upstream proxy' });
  }
});

// Update upstream proxy
router.put('/:id', authMiddleware, adminMiddleware, async (req: AuthRequest, res) => {
  try {
    const proxy = await UpstreamProxy.findByPk(req.params.id);

    if (!proxy) {
      return res.status(404).json({ error: 'Upstream proxy not found' });
    }

    const { name, type, host, port, username, password, country, city, provider, enabled, priority } = req.body;

    await proxy.update({
      name: name !== undefined ? name : proxy.name,
      type: type !== undefined ? type : proxy.type,
      host: host !== undefined ? host : proxy.host,
      port: port !== undefined ? port : proxy.port,
      username: username !== undefined ? username : proxy.username,
      password: password !== undefined ? password : proxy.password,
      country: country !== undefined ? country : proxy.country,
      city: city !== undefined ? city : proxy.city,
      provider: provider !== undefined ? provider : proxy.provider,
      enabled: enabled !== undefined ? enabled : proxy.enabled,
      priority: priority !== undefined ? priority : proxy.priority,
    });

    // Regenerate Squid config
    try {
      const config = await generateUpstreamConfig();
      await writeFile(UPSTREAM_CONFIG_PATH, config);
      console.log('Upstream config regenerated');
    } catch (configError) {
      console.error('Failed to update Squid config:', configError);
    }

    res.json({
      ...proxy.toJSON(),
      password: undefined,
    });
  } catch (error) {
    console.error('Upstream update error:', error);
    res.status(500).json({ error: 'Failed to update upstream proxy' });
  }
});

// Delete upstream proxy
router.delete('/:id', authMiddleware, adminMiddleware, async (req: AuthRequest, res) => {
  try {
    const proxy = await UpstreamProxy.findByPk(req.params.id);

    if (!proxy) {
      return res.status(404).json({ error: 'Upstream proxy not found' });
    }

    await proxy.destroy();

    // Regenerate Squid config
    try {
      const config = await generateUpstreamConfig();
      await writeFile(UPSTREAM_CONFIG_PATH, config);
      console.log('Upstream config regenerated');
    } catch (configError) {
      console.error('Failed to update Squid config:', configError);
    }

    res.json({ message: 'Upstream proxy deleted' });
  } catch (error) {
    console.error('Upstream delete error:', error);
    res.status(500).json({ error: 'Failed to delete upstream proxy' });
  }
});

export default router;
